server.address=localhost
system.setup.and.testing.api.enabled: true

mail.template.parameters.rpkiDashboardUri=https://dashboard.qa-01.rpki.prepdev.ripe.net
mail.template.parameters.authUnsubscribeUri=https://access.prepdev.ripe.net/?originalUrl=
mail.template.parameters.apiUnsubscribeUri=https://my.prepdev.ripe.net/api/rpki/unsubscribe-alerts

online.repository.directory=/cert/repository/repository
ta.repository.directory=/cert/repository/ta
online.repository.notification.uri=https://qa-01.rpki.prepdev.ripe.net/rrdp/notification.xml

# The externally visible URI for the public certificate repository. This URI
# will be included in generated certificates as AIA and SIA extensions.
online.repository.uri=rsync://qa-01.rpki.prepdev.ripe.net/repository/
ta.repository.uri=rsync://qa-01.rpki.prepdev.ripe.net/ta/

# Keystore settings
#
# settings for software keys
keystore.provider=SUN
keypair.generator.provider=SunRsaSign
signature.provider=SunRsaSign
keystore.type=JKS

# settings for HSM keys
#keystore.provider=nCipherKM
#keypair.generator.provider=nCipherKM
#signature.provider=nCipherKM
#keystore.type=ncipher.sworld

#keystore.provider=DBProvider
#keypair.generator.provider=DBProvider
#signature.provider=DBProvider
#keystore.type=nCipher.database

# Remote Services
resource.services.url=https://rsng.prepdev.ripe.net/resource-services

prometheus.base.url=https://prometheus.rpki.prepdev.ripe.net/

# Customer Service Backend
customer.service.url=https://ba-apps.prepdev.ripe.net/customer-service

key.management.data.directory=/cert/hsmkeys/shared-keys
key.management.data.archive.directory=/cert/hsmkeys/shared-keys.archive

autokeyrollover.enable=false
autokeyrollover.maxage.days=1
autokeyrollover.update.interval.days=2
# All in one batch - we want to recover ASAP
keypair.keyroll.batch.size=1000000

# Deployment environment banner
static.image.deployment.environment=static/images/cert_staging.png

# Non-hosted, must also work over plain http
provisioning.base.url=http://qa-01.rpki.prepdev.ripe.net/certification/updown

# auth service
auth.service.url=https://ba-apps.prepdev.ripe.net/authorisation-service

publication.client.keystore=/cert/shared/clientKeyStore.ks
publication.client.truststore=/cert/shared/clientTrustStore.ks

logging.config=classpath:logback/logback-prepdev.xml

api-keys.properties=file:///cert/shared/rpki-api-keys.properties

# This is to enable manual service that cleans up CAs without key pair and any activity
certificate.authority.cleanup.service.enabled=true

non-hosted.publisher.repository.enabled=false

certificate.authority.invariant.checking.enabled=true
