logging.config: classpath:logback/logback-local.xml

signature:
    provider: SunRsaSign

keystore:
    provider: SUN
    type: JKS

instance.name: local
system.setup.and.testing.api.enabled: true

# local setup should not be able to deliver mail by default.
mail:
    host: localhost
    port: 1025

spring:
    main:
        lazy-initialization: true
    datasource:
        password: certdb
        url: jdbc:postgresql://localhost:5432/certdb
    devtools.livereload.enabled: false
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/WEB-INF/templates/

background-services:
    schedule.enable: false

#
# Integrations
#
auth.service:
    url: https://ba-apps.prepdev.ripe.net/authorisation-service
    # wlog: the api.key values in this file are not secrets and are intentionally included
    # in this (public) repository.
    #
    # @see https://www.youtube.com/watch?v=dQw4w9WgXcQ
    api.key: BAD-TEST-D2Shtf2n5Bwh02P7

customer.service:
    url: https://ba-apps.prepdev.ripe.net/customer-service
    # intentionally included/not a secret
    api.key: BAD-TEST-D2Shtf2n5Bwh02P7

resource.services:
    url: https://rsng.prepdev.ripe.net/resource-services
    # intentionally included/not a secret
    apiKey: BAD-TEST-D2Shtf2n5Bwh02P7

#
# Application specific settings
#
authorization.admin.role: ROLE_ANONYMOUS
# We externalise application secrets in a file outside the application on the classpath.
api-keys.properties: "classpath:/test-api-keys.properties"

intermediate.ca:
    use.inherited.resources: true

autokeyrollover:
    maxage.days: 0
    update.interval.days: 10


key.management.data:
    archive.directory: /tmp
    directory: /tmp

# lower these intervals for local environment
keypair:
    activation:
        delay.hours: 0
        interval.hours: 240
    revocation.interval.hours: 240
    generator.provider: SunRsaSign
    # All in one batch - we want to recover ASAP
    keyroll.batch.size: 1000000

online.repository:
    notification.uri: https://localhost:7788/notification.xml
    directory: ${HOME}/export/bad/certification/repository/online
    uri: rsync://localhost:10873/repository/

provisioning.base.url: http://localhost.ripe.net:8080/certification/updown

manifest.crl.update.interval.minutes: 10

# Write rsync more frequently locally
public.repository.rsync.interval.minutes: 5

publication:
    client:
        keystore: ${RIPE_PUBLICATION_SERVER_SRC_PATH:${HOME}/src/ripe/rpki/rpki-publication-server}/src/test/resources/certificates/clientKeyStore.ks
        keystore.password: 123456
        truststore: ${RIPE_PUBLICATION_SERVER_SRC_PATH:${HOME}/src/ripe/rpki/rpki-publication-server}/src/test/resources/certificates/clientTrustStore.ks
        truststore.password: 123456
    server.url: https://localhost:7766/

riswhoisdump:
    base.url: http://localhost:8080/certification/static/dev-ris
    update.interval.hours: 1

ta.repository:
    directory: ${HOME}/export/bad/certification/repository/ta
    uri: rsync://localhost:10873/ta/


non-hosted:
  publisher:
    repository:
      enabled: true
      url: "https://internal.paas.rpki.prepdev.ripe.net/"
      token: "krill-dev-token"


certificate.authority:
    cleanup.service.enabled: true
    invariant.checking.enabled: true
    update.batch.size: 1000000
