package net.ripe.rpki.domain.interca;

import lombok.NonNull;
import lombok.Value;
import lombok.With;
import net.ripe.rpki.commons.crypto.rfc3779.ResourceExtension;
import net.ripe.rpki.commons.crypto.x509cert.X509CertificateInformationAccessDescriptor;

import javax.security.auth.x500.X500Principal;
import java.security.PublicKey;

/**
 * This class does not represent any RFC and used for internal request-response modelling
 * of hosted CAs parent-child interaction.
 *
 * <p>CertificateIssuanceRequest is to be generated by a child CA that wants to have a new
 * certificate issued by the parent CA.</p>
 */
@Value
@With
public class CertificateIssuanceRequest implements CertificateProvisioningMessage {

    @NonNull ResourceExtension resourceExtension;
    @NonNull X500Principal subjectDN;
    @NonNull PublicKey subjectPublicKey;
    @NonNull X509CertificateInformationAccessDescriptor[] subjectInformationAccess;

}
