package net.ripe.rpki.domain.interca;

import lombok.Value;

import java.security.PublicKey;

import static java.util.Objects.requireNonNull;

/**
 * This class does not represent any RFC and used for internal request-response modelling
 * of hosted CAs parent-child interaction.
 *
 * CertificateRevocationRequest is to be generated by a child CA that wants its certificate
 * to be revoked by the parent CA.
 */
@Value
public class CertificateRevocationRequest implements CertificateProvisioningMessage {

    PublicKey subjectPublicKey;

    public CertificateRevocationRequest(PublicKey subjectPublicKey) {
        this.subjectPublicKey = requireNonNull(subjectPublicKey, "subjectPublicKey is required");
    }
}
