plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    maven {
      url = "https://plugins.gradle.org/m2/"
    }
}

dependencies {
    implementation 'io.freefair.lombok:io.freefair.lombok.gradle.plugin:9.5.0'
    implementation 'com.gorylenko.gradle-git-properties:com.gorylenko.gradle-git-properties.gradle.plugin:4.0.1'
    implementation 'org.eclipse.jgit:org.eclipse.jgit:7.7.1.202607240634-r'
    implementation 'org.sonarqube:org.sonarqube.gradle.plugin:7.4.0.8496'
}
