name: JUnit Tests 
on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    # runs-on: gradle:7.5.1-jdk8
    services:
      postgres:
        image: postgres:12.13
        env:
          POSTGRES_USER: certdb
          POSTGRES_PASSWORD: certdb
          POSTGRES_DB: certdb_test
        ports:          
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JUnit Tests            
          path: 'build/test-results/test/TEST-*.xml'
          reporter: java-junit